apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-oqne
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-oqne
    app.kubernetes.io/part-of: my-app-nm
  name: devfile-sample-oqne
  namespace: nmukherj-tenant
spec:
  ports:
  - port: 3002
    targetPort: 3002
  selector:
    app.kubernetes.io/instance: devfile-sample-oqne
status:
  loadBalancer: {}
